steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/shopping-497906/shopping-memo/backend:latest'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/shopping-497906/shopping-memo/backend:$BUILD_ID'
      - '.'
    dir: 'backend'

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/shopping-497906/shopping-memo/backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'shopping-memo-backend'
      - '--image'
      - 'asia-southeast1-docker.pkg.dev/shopping-497906/shopping-memo/backend:latest'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'SUPABASE_URL=https://akyxznfvwogxhcwocukj.supabase.co,SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFreXh6bmZ2d29neGhjd29jdWtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ2NTM1ODYsImV4cCI6MjA5MDIyOTU4Nn0.w_hwdPW-_OuBBc4OU-Hi3nq-0kuD3Hy2IyTH8jlmS9w,SUPABASE_JWT_SECRET=fmzXffg+8+EtOm8o54Fa2EdnV6PYEsT0l+l5XcaPKPaSLq5Pz8MiDdKxCYij+GD7dqtUxL5oYW0dizQSO+Zldg==,APP_ENV=production'
      - '--set-secrets'
      - 'SUPABASE_SERVICE_ROLE_KEY=supabase:latest'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '0.5'
      - '--timeout'
      - '60'
      - '--max-instances'
      - '20'

images:
  - 'asia-southeast1-docker.pkg.dev/shopping-497906/shopping-memo/backend:latest'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
